gg  : "(o)"                     -> empty
    | part "->" part ":" msg    -> interaction
    | gg "|" gg                 -> fork
    | "sel" "{" gg "+" gg "}"     -> choice
    | gg ";" gg                 -> sequential
    | "repeat" "{" gg "}"       -> iteration

part: CNAME
msg: CNAME

COMMENT: "//" /[^\n]*/ NEWLINE?
%ignore COMMENT

%import common.CNAME
%import common.WS
%import common.NEWLINE
%ignore WS
